FROM golang:1.25

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends nodejs npm \
    && npm install -g pnpm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN grep -qxF "alias ll='ls -alF'" /root/.bashrc || echo "alias ll='ls -alF'" >> /root/.bashrc

WORKDIR /go/src/domrank
